- name: Analyze bundle sizes
  uses: transferwise/actions-next-bundle-analyzer@v2
  with:
    # Optional, specifies where to look for .next folder. Defaults to cwd.
    working-directory: ./
    # Optional, configures commenting strategy around insignificant changes, defaults to `always`.
    # Available options:
    #   always: Always comment on PRs, even if it's just to say there are no significant changes.
    #   skip-insignificant: Skip commenting on PRs if there are no signficant changes in page sizes.
    comment-strategy: 'always'
    # Optional, configures whether to create the bundle size summary issue, defaults to `true`.
    # Available options:
    #   true
    #   false
    create-issue: true
    # Optional, defaults to `github.token`.
    github-token: ${{ secrets.GITHUB_TOKEN }}